[34m[1mtrain: [39m[22mweights=yolov5s.pt, cfg=/content/yolov5/models/yolov5s.yaml, data=/content/drive/MyDrive/OCR Project(SMU)/emnist_data.yaml, hyp=/content/yolov5/data/hyps/hyp.scratch.yaml, epochs=10, batch_size=64, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs/train, entity=None, name=yolo_emnist_det, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=-1, freeze=0
[34m[1mgithub: [39m[22mskipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5
YOLOv5 üöÄ v5.0-374-g1d65e81 torch 1.9.0+cu102 CPU
[34m[1mhyperparameters: [39m[22mlr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
[34m[1mTensorBoard: [39m[22mStart with 'tensorboard --logdir runs/train', view at http://localhost:6006/
[34m[1mwandb[39m[22m: Currently logged in as: [33mlesterye[39m (use `wandb login --relogin` to force relogin)
[34m[1mwandb[39m[22m: Tracking run with wandb version 0.12.0
[34m[1mwandb[39m[22m: Syncing run [33myolo_emnist_det
[34m[1mwandb[39m[22m: ‚≠êÔ∏è View project at [34m[4mhttps://wandb.ai/lesterye/YOLOv5
[34m[1mwandb[39m[22m: üöÄ View run at [34m[4mhttps://wandb.ai/lesterye/YOLOv5/runs/1cmmut4b
[34m[1mwandb[39m[22m: Run data is saved locally in /content/drive/My Drive/OCR Project(SMU)/wandb/run-20210818_140101-1cmmut4b
[34m[1mwandb[39m[22m: Run `wandb offline` to turn off syncing.
Overriding model.yaml nc=80 with nc=47
                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  3    156928  models.common.C3                        [128, 128, 3]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  3    625152  models.common.C3                        [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 24      [17, 20, 23]  1    140244  models.yolo.Detect                      [47, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7187604 parameters, 7187604 gradients, 16.8 GFLOPs
Transferred 354/362 items from yolov5s.pt
Scaled weight_decay = 0.0005
[34m[1moptimizer:[39m[22m SGD with parameter groups 59 weight, 62 weight (no decay), 62 bias
[34m[1malbumentations: [39m[22mversion 1.0.3 required by YOLOv5, but version 0.1.12 is currently installed


















































































































[34m[1mtrain: [39m[22mScanning '/content/drive/MyDrive/OCR Project(SMU)/labels/train' images and labels...826 found, 0 missing, 0 empty, 0 corrupted:   5% 826/16000 [03:49<1:10:08,  3.61it/s]
Traceback (most recent call last):
  File "/content/yolov5/utils/datasets.py", line 407, in __init__
    assert cache['version'] == 0.4 and cache['hash'] == get_hash(self.label_files + self.img_files)
AssertionError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 733, in next
    item = self._items.popleft()
IndexError: pop from an empty deque
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/content/yolov5/utils/datasets.py", line 492, in cache_labels
    for im_file, l, shape, segments, nm_f, nf_f, ne_f, nc_f, msg in pbar:
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1185, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 737, in next
    self._cond.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/content/yolov5/train.py", line 602, in <module>
    main(opt)
  File "/content/yolov5/train.py", line 500, in main
    train(opt.hyp, opt, device)
  File "/content/yolov5/train.py", line 208, in train
    prefix=colorstr('train: '))
  File "/content/yolov5/utils/datasets.py", line 107, in create_dataloader
    prefix=prefix)
  File "/content/yolov5/utils/datasets.py", line 409, in __init__
    cache, exists = self.cache_labels(cache_path, prefix), False  # cache
  File "/content/yolov5/utils/datasets.py", line 501, in cache_labels
    pbar.desc = f"{desc}{nf} found, {nm} missing, {ne} empty, {nc} corrupted"
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 623, in __exit__
    self.terminate()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 548, in terminate
    self._terminate()
  File "/usr/lib/python3.7/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 581, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 568, in _help_stuff_finish
    inqueue._reader.recv()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Process ForkPoolWorker-3:
Traceback (most recent call last):
  File "/content/yolov5/utils/datasets.py", line 407, in __init__
    assert cache['version'] == 0.4 and cache['hash'] == get_hash(self.label_files + self.img_files)
AssertionError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/content/yolov5/utils/datasets.py", line 867, in verify_image_label
    im = Image.open(im_file)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2852, in open
    prefix = fp.read(16)
KeyboardInterrupt
Process ForkPoolWorker-2:
Traceback (most recent call last):
  File "/content/yolov5/utils/datasets.py", line 407, in __init__
    assert cache['version'] == 0.4 and cache['hash'] == get_hash(self.label_files + self.img_files)
AssertionError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/content/yolov5/utils/datasets.py", line 882, in verify_image_label
    l = [x.split() for x in f.read().strip().splitlines() if len(x)]
  File "/usr/lib/python3.7/codecs.py", line 319, in decode
    def decode(self, input, final=False):
KeyboardInterrupt
[34m[1mwandb[39m[22m: Waiting for W&B process to finish, PID 1235
[34m[1mwandb[39m[22m: Program failed with code 255.  Press ctrl-c to abort syncing.
[34m[1mwandb[39m[22m:
[34m[1mwandb[39m[22m: Find user logs for this run at: /content/drive/My Drive/OCR Project(SMU)/wandb/run-20210818_140101-1cmmut4b/logs/debug.log
[34m[1mwandb[39m[22m: Find internal logs for this run at: /content/drive/My Drive/OCR Project(SMU)/wandb/run-20210818_140101-1cmmut4b/logs/debug-internal.log
[34m[1mwandb[39m[22m: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
[34m[1mwandb[39m[22m:
[34m[1mwandb[39m[22m: Synced [33myolo_emnist_det[39m: [34mhttps://wandb.ai/lesterye/YOLOv5/runs/1cmmut4b
/content/yolov5
/content/yolov5
Traceback (most recent call last):
  File "/content/yolov5/test.py", line 18, in <module>
    from utils.torch_utils import select_device, time_synchronized
ImportError: cannot import name 'time_synchronized' from 'utils.torch_utils' (/content/yolov5/utils/torch_utils.py)
[34m[1mtrain: [39m[22mweights=yolov5s.pt, cfg=/content/yolov5/models/yolov5s.yaml, data=/content/drive/MyDrive/OCR Project(SMU)/emnist_data.yaml, hyp=/content/yolov5/data/hyps/hyp.scratch.yaml, epochs=3, batch_size=64, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, adam=False, sync_bn=False, workers=8, project=runs/train, entity=None, name=yolo_emnist_det, exist_ok=False, quad=False, linear_lr=False, label_smoothing=0.0, upload_dataset=False, bbox_interval=-1, save_period=-1, artifact_alias=latest, local_rank=-1, freeze=0
[34m[1mgithub: [39m[22mup to date with https://github.com/ultralytics/yolov5 ‚úÖ
YOLOv5 üöÄ v5.0-374-g1d65e81 torch 1.9.0+cu102 CPU
[34m[1mhyperparameters: [39m[22mlr0=0.01, lrf=0.2, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
[34m[1mTensorBoard: [39m[22mStart with 'tensorboard --logdir runs/train', view at http://localhost:6006/
[34m[1mwandb[39m[22m: Currently logged in as: [33mlesterye[39m (use `wandb login --relogin` to force relogin)
[34m[1mwandb[39m[22m: Tracking run with wandb version 0.12.0
[34m[1mwandb[39m[22m: Syncing run [33myolo_emnist_det
[34m[1mwandb[39m[22m: ‚≠êÔ∏è View project at [34m[4mhttps://wandb.ai/lesterye/YOLOv5
[34m[1mwandb[39m[22m: üöÄ View run at [34m[4mhttps://wandb.ai/lesterye/YOLOv5/runs/3oaysdfy
[34m[1mwandb[39m[22m: Run data is saved locally in /content/yolov5/wandb/run-20210818_141237-3oaysdfy
[34m[1mwandb[39m[22m: Run `wandb offline` to turn off syncing.
Overriding model.yaml nc=80 with nc=47
                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  3    156928  models.common.C3                        [128, 128, 3]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  3    625152  models.common.C3                        [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]
  9                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 24      [17, 20, 23]  1    140244  models.yolo.Detect                      [47, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 283 layers, 7187604 parameters, 7187604 gradients, 16.8 GFLOPs
Transferred 354/362 items from yolov5s.pt
Scaled weight_decay = 0.0005
[34m[1moptimizer:[39m[22m SGD with parameter groups 59 weight, 62 weight (no decay), 62 bias
[34m[1malbumentations: [39m[22mversion 1.0.3 required by YOLOv5, but version 0.1.12 is currently installed
[34m[1mtrain: [39m[22mScanning '/content/drive/MyDrive/OCR Project(SMU)/labels/train.cache' images and labels... 16000 found, 0 missing, 0 empty, 0 corrupted: 100% 16000/16000 [00:00<?, ?it/s]
[34m[1mval: [39m[22mScanning '/content/drive/MyDrive/OCR Project(SMU)/labels/val.cache' images and labels... 2000 found, 0 missing, 0 empty, 0 corrupted: 100% 2000/2000 [00:00<?, ?it/s]
Plotting labels...
[34m[1mautoanchor: [39m[22mAnalyzing anchors... anchors/target = 2.99, Best Possible Recall (BPR) = 0.9862
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs/train/yolo_emnist_det2
Starting training for 3 epochs...
     Epoch   gpu_mem       box       obj       cls    labels  img_size
  0% 0/250 [00:00<?, ?it/s]/usr/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 6 leaked semaphores to clean up at shutdown
  len(cache))
^C
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>> (for pre_run_cell):
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/wandb_run.py", line 198, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 737, in communicate_stop_status
    resp = self._communicate(req, timeout=timeout, local=True)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 539, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.7/dist-packages/wandb/sdk/interface/interface.py", line 544, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Traceback (most recent call last):
  File "/content/yolov5/train.py", line 32, in <module>
    import val  # for end-of-epoch mAP
  File "/content/yolov5/val.py", line 23, in <module>
    from models.experimental import attempt_load
  File "/content/yolov5/models/experimental.py", line 10, in <module>
    from models.common import Conv
  File "/content/yolov5/models/common.py", line 20, in <module>
    from utils.datasets import exif_transpose, letterbox
  File "/content/yolov5/utils/datasets.py", line 28, in <module>
    from utils.augmentations import Albumentations, augment_hsv, copy_paste, letterbox, mixup, random_perspective
  File "/content/yolov5/utils/augmentations.py", line 13, in <module>
    from utils.general import colorstr, segment2box, resample_segments, check_version
  File "/content/yolov5/utils/general.py", line 25, in <module>
    import pkg_resources as pkg
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3242, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 559, in _build_master
    ws = cls()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 552, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 608, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2063, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2121, in distributions_from_metadata
    if len(os.listdir(path)) == 0:
KeyboardInterrupt
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>> (for post_run_cell):
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>> (for pre_run_cell):
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>> (for post_run_cell):
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>> (for pre_run_cell):
Requirement already satisfied: wandb in /usr/local/lib/python3.7/dist-packages (0.12.0)
Requirement already satisfied: promise<3,>=2.0 in /usr/local/lib/python3.7/dist-packages (from wandb) (2.3)
Requirement already satisfied: sentry-sdk>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from wandb) (1.3.1)
Requirement already satisfied: configparser>=3.8.1 in /usr/local/lib/python3.7/dist-packages (from wandb) (5.0.2)
Requirement already satisfied: GitPython>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from wandb) (3.1.18)
Requirement already satisfied: Click!=8.0.0,>=7.0 in /usr/local/lib/python3.7/dist-packages (from wandb) (7.1.2)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from wandb) (2.23.0)
Requirement already satisfied: shortuuid>=0.5.0 in /usr/local/lib/python3.7/dist-packages (from wandb) (1.0.1)
Requirement already satisfied: docker-pycreds>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from wandb) (0.4.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.7/dist-packages (from wandb) (5.4.1)
Requirement already satisfied: protobuf>=3.12.0 in /usr/local/lib/python3.7/dist-packages (from wandb) (3.17.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.7/dist-packages (from wandb) (2.8.2)
Requirement already satisfied: subprocess32>=3.5.3 in /usr/local/lib/python3.7/dist-packages (from wandb) (3.5.4)
Requirement already satisfied: pathtools in /usr/local/lib/python3.7/dist-packages (from wandb) (0.1.2)
Requirement already satisfied: six>=1.13.0 in /usr/local/lib/python3.7/dist-packages (from wandb) (1.15.0)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from wandb) (5.4.8)
Requirement already satisfied: typing-extensions>=3.7.4.0 in /usr/local/lib/python3.7/dist-packages (from GitPython>=1.0.0->wandb) (3.7.4.3)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.7/dist-packages (from GitPython>=1.0.0->wandb) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in /usr/local/lib/python3.7/dist-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.0->wandb) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.0.0->wandb) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.0.0->wandb) (2021.5.30)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.0.0->wandb) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3,>=2.0.0->wandb) (3.0.4)
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>> (for post_run_cell):
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>> (for pre_run_cell):
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>> (for post_run_cell):
[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.login() after wandb.init() has no effect.
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>> (for pre_run_cell):
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>> (for post_run_cell):
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7fbee97d9c90>> (for pre_run_cell):